updating cloud formation jobs with instance template and adding an extra instance

diff --git a/main.yml b/main.yml
--- a/main.yml
+++ b/main.yml
@@ -25,7 +25,6 @@ Parameters:
     Description: 'A GitHub personal access token with "repo" and "admin:repo_hook" permissions.'
 
 Resources:
-
   SecurityGroup:
       Type: AWS::EC2::SecurityGroup
       Properties:
@@ -57,6 +56,14 @@ Resources:
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/CloudWatchFullAccess
         - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
+      Policies:
+        - PolicyName: ec2DescribeTags
+          PolicyDocument:
+            Version: 2012-10-17
+            Statement:
+              - Effect: Allow
+                Action: 'ec2:DescribeTags'
+                Resource: '*'
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
@@ -67,18 +74,15 @@ Resources:
       Roles:
         - Ref: InstanceRole
 
-  Instance:
-    Type: AWS::EC2::Instance
-    CreationPolicy:
-      ResourceSignal:
-        Timeout: PT5M
-        Count: 1
+  InstanceLaunchTemplate:
+    Type: AWS::EC2::LaunchTemplate
     Metadata:
       AWS::CloudFormation::Init:
         config:
           packages:
             yum:
               ruby: []
+              jq: []
           files:
             /home/ec2-user/install:
               source: !Sub "https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install"
@@ -88,26 +92,29 @@ Resources:
               command: "./install auto"
               cwd: "/home/ec2-user/"
     Properties:
-      ImageId: !Ref EC2AMI
-      InstanceType: !Ref EC2InstanceType
-      IamInstanceProfile: !Ref InstanceProfile
-      Monitoring: true
-      SecurityGroupIds:
-        - !GetAtt SecurityGroup.GroupId
-      UserData:
-        Fn::Base64: !Sub |
-          #!/bin/bash -xe
+      LaunchTemplateName: !Sub 'LaunchTemplate_${AWS::StackName}'
+      LaunchTemplateData:
+        ImageId: !Ref EC2AMI
+        InstanceType: !Ref EC2InstanceType
+        IamInstanceProfile:
+          Arn: !GetAtt InstanceProfile.Arn
+        Monitoring:
+          Enabled: true
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        UserData:
+          Fn::Base64: !Sub |
+            #!/bin/bash -xe
+            # send script output to /tmp so we can debug boot failures
+            exec > /tmp/userdata.log 2>&1
 
-          # send script output to /tmp so we can debug boot failures
-          exec > /tmp/userdata.log 2>&1
+            # Update all packages
+            yum -y update
 
-          # Update all packages
-          yum -y update
+            # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
+            yum install -y aws-cfn-bootstrap
 
-          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#cfninit
-          yum install -y aws-cfn-bootstrap
-
-          cat > /tmp/install_script.sh << EOF
+            cat > /tmp/install_script.sh << EOF
             # START
             echo "Setting up NodeJS Environment"
             curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
@@ -121,31 +128,60 @@ Resources:
             nvm install v12.7.0
             nvm use v12.7.0
 
-            # Download latest code, unzip it into /home/ec2-user/app
-            #wget https://github.com/{{username}}/aws-bootstrap/archive/master.zip
-            #unzip master.zip
-            #mv aws-bootstrap-master app
-
             # Create log directory
             mkdir -p /home/ec2-user/app/logs
+            EOF
 
-            # Run server
-            #cd app
-            #npm install
-            #npm start
-          EOF
+            chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
+            sleep 1; su - ec2-user -c "/tmp/install_script.sh"
 
-          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
-          sleep 1; sudo su - ec2-user -c "/tmp/install_script.sh"
+            # Have CloudFormation install any files and packages from the metadata
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource InstanceLaunchTemplate
 
-          # Have CloudFormation install any files and packages from the metadata
-          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
-          # Signal to CloudFormation that the instance is ready
-          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+            # Query the EC2 metadata service for this instance's instance-id
+            export INSTANCE_ID="`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`"
 
+            # Query EC2 describeTags method and pull our the CFN Logical ID for this instance
+            export LOGICAL_ID=`aws --region ${AWS::Region} ec2 describe-tags \
+            --filters "Name=resource-id,Values=${!INSTANCE_ID}" \
+            "Name=key,Values=aws:cloudformation:logical-id" \
+            | jq -r ".Tags[0].Value"`
+
+            # Signal to CloudFormation that the instance is ready
+            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource ${!LOGICAL_ID}
+
+  Instance:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
+
+  Instance2:
+    Type: AWS::EC2::Instance
+    CreationPolicy:
+      ResourceSignal:
+        Timeout: PT5M
+        Count: 1
+    Properties:
+      LaunchTemplate:
+        LaunchTemplateId: !Ref InstanceLaunchTemplate
+        Version: !GetAtt InstanceLaunchTemplate.LatestVersionNumber
+      Tags:
+        - Key: Name
+          Value: !Ref AWS::StackName
+
+
+  # ------- build pipeline resources
+  # Deployment role to give application access to code pipeline, code deploy, code build
+  # Resources for code build project, deployment application, deployment group & web hook
 
 
   DeploymentRole:
@@ -163,7 +199,6 @@ Resources:
           Action: sts:AssumeRole
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/PowerUserAccess
-
 
   BuildProject:
     Type: AWS::CodeBuild::Project
@@ -254,7 +289,6 @@ Resources:
                 DeploymentGroupName: !Ref StagingDeploymentGroup
               RunOrder: 1
 
-
   PipelineWebhook:
     Type: AWS::CodePipeline::Webhook
     Properties:
@@ -263,7 +297,7 @@ Resources:
         SecretToken: !Ref GitHubPersonalAccessToken
       Filters:
         - JsonPath: $.ref
-          MatchEquals: 'refs/heads/{GitHubBranch}'
+          MatchEquals: 'refs/heads/{Branch}'
       TargetPipeline: !Ref Pipeline
       TargetAction: Source
       Name: !Sub 'webhook-${AWS::StackName}'
@@ -273,8 +307,14 @@ Resources:
 
 
 Outputs:
-  InstanceEndpoint:
+  InstanceEndpoint1:
     Description: The DNS name for the created instance
     Value: !Sub "http://${Instance.PublicDnsName}:8080"
     Export:
-      Name: InstanceEndpoint
+      Name: InstanceEndpoint1
+
+  InstanceEndpoint2:
+    Description: The DNS name for the created instance
+    Value: !Sub "http://${Instance2.PublicDnsName}:8080"
+    Export:
+      Name: InstanceEndpoint2
